version: '3.8'
services:
  postgres:
    image: 'postgres:14.2'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - '.env'
    ports:
      - '5432:5432'
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
  web:
    entrypoint: [bin/entry]
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4001 -b '0.0.0.0' -e ${ENVIRONMENT}"
    volumes:
      - .:/powerbase-server
    ports:
      - "4001:4001"
    env_file:
      - '.env'
    depends_on:
      - 'postgres'
      - 'redis'
  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bundle exec sidekiq -e ${ENVIRONMENT} -c 3
    env_file:
      - '.env'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - cluster.name=elasticsearch-rails
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
volumes:
  redis:
  postgres: