version: '3.8'
services:
  postgres:
    image: 'postgres:14.2'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=powerbase
    ports:
      - '5432:5432'
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - cluster.name=elasticsearch-rails
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  web_socket:
    image: edgurgel/poxa-automated:latest
    environment:
      - PORT=6001
      - POXA_APP_ID=${PUSHER_APP_ID}
      - POXA_APP_KEY=${PUSHER_KEY}
      - POXA_SECRET=${PUSHER_SECRET}
    ports:
      - "6001:6001"
  server:
    entrypoint: [bin/entry]
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4001 -b '0.0.0.0' -e ${RAILS_ENV}"
    volumes:
      - .:/powerbase-server
    ports:
      - "4001:4001"
    env_file:
      - '.env'
    depends_on:
      - 'postgres'
      - 'redis'
      - 'elasticsearch'
      - 'web_socket'
  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'elasticsearch'
      - 'web_socket'
    build: .
    command: bundle exec sidekiq -e ${RAILS_ENV} -c 3
    env_file:
      - '.env'
volumes:
  redis:
  postgres: