CLIENT: "http://localhost:4000"
AUTH_TOKEN_ENCRYPTION_KEY: "secret"

encryption_key: "secret"
jwt_encryption_key: "secret"
API_ENCRYPTION_KEY: "some_32_character_secret_1234567"
redis_url: "redis://localhost:6379/0"
elasticsearch_url: "http://localhost:9200"
hubspot_api_key: ""

PUSHER_KEY: ""
PUSHER_SECRET: ""
PUSHER_APP_ID: ""
ENABLE_LISTENER: ""

POSTMARK_API_TOKEN: ""
SENTRY_DSN: ""
ENABLE_SENTRY:

SAMPLE_DATABASE_ID: ""

AWS_DATABASE_HOST: ""
AWS_DATABASE_CONNECTION: ""
