client: "http://localhost:4000"
encryption_key: "secret"
jwt_encryption_key: "secret"
redis_url: "redis://localhost:6379/0"
elasticsearch_url_development: "http://localhost:9200"
hubspot_api_key: ""
elasticsearch_url: ""

PUSHER_KEY: "1fa8e84feca07575f40d"
PUSHER_SECRET: "3484070215788ad6455f"
PUSHER_APP_ID: "1277145"
ENABLE_LISTENER: true
