CLIENT: "http://localhost:4000"
AUTH_TOKEN_ENCRYPTION_KEY: "secret"

encryption_key: "secret"
jwt_encryption_key: "secret"
redis_url: "redis://localhost:6379/0"
elasticsearch_url_development: "http://localhost:9200"
hubspot_api_key: ""
elasticsearch_url: ""

PUSHER_KEY: ""
PUSHER_SECRET: ""
PUSHER_APP_ID: ""
ENABLE_LISTENER: ""

POSTMARK_API_TOKEN: ""
SENTRY_DSN: ""

SAMPLE_DATABASE_ID: ""