CLIENT: "http://localhost:4000"
AUTH_TOKEN_ENCRYPTION_KEY: "secret"
SECRET_KEY_BASE: ""

DATABASE_URL: "postgres://insert_postgres_username_here:insert_postgres_password_here@host.docker.internal:5432/powerbase"
encryption_key: "secret"
jwt_encryption_key: "secret"
API_ENCRYPTION_KEY: "some_32_character_secret_1234567"

REDIS_URL: "redis://:insert_redis_password_here@host.docker.internal:6379/0"
ELASTICSEARCH_URL: "host.docker.internal:9200"
hubspot_api_key: ""

PUSHER_KEY: ""
PUSHER_SECRET: ""
PUSHER_APP_ID: ""
ENABLE_LISTENER: "true"

POSTMARK_API_TOKEN: ""
SENTRY_DSN: ""
ENABLE_SENTRY: "false"

SAMPLE_DATABASE_ID: "1"

AWS_DATABASE_HOST: "host.docker.internal:5432"
AWS_DATABASE_CONNECTION: "postgres://powerbase_app:insert_powerbase_app_password_here@host.docker.internal:5432/powerbase"
