default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 100 } %>

production:
    <<: *default
    database: powerbase

development:
  <<: *default
  database: powerbase

test:
  <<: *default
  database: powerbase_test
