default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
    <<: *default
    database: powerbase

development:
  <<: *default
  database: powerbase

test:
  <<: *default
  database: powerbase_test
