name: Sync To Server Repo
on:
  push:
    branches:
      - main
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Repo
        run: |
          git fetch
          git remote add server git@github.com:Group-One-Technology/powerbase-server.git
          git push -f server main

