name: Sync To Server Repo
on:
  push:
    branches:
      - main
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: publish:starters
        uses: johno/actions-push-subdirectories@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: powerbase-server Group-One-Technology powerbase-server main
